# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
This function is not safe. This is because based on the argument that was passed into the function a error would occur, and in this function there is not .then to catch the resolved, and no .catch to handle the rejections. Not sure what would happen when a error is passsed in this case but im sure that it would response in a way that we would not like. 

# Teacher Feedback